### PR TITLE
fix: NextJS options type

### LINKED ISSUE #9: fix: make options type shareable between packages
i ran into some weird inference issues when the next.js package extended the core package options type - should be fixed to avoid a bunch of duplications

### PR DESCRIPTION
**Pull request by chungweileong94**
fix #9 

- Improved NextJS options type

### CODE REVIEW

File: packages/nextjs/index.ts [hunk 1]
```diff
@@ -1,67 +1,29 @@
...
-   * built with invalid env vars. To expose them to the client, prefix them with `NEXT_PUBLIC_`.
-   */
-  client: {
-    [TKey in keyof TClient]: TKey extends `NEXT_PUBLIC_${string}`
-      ? TClient[TKey]
-      : ErrorMessage<`${TKey extends string
-          ? TKey
-          : never} is not prefixed with NEXT_PUBLIC_.`>;
-  };
+type ClientPrefix = "NEXT_PUBLIC_";
```
Comment (juliusmarminge) [inline packages/nextjs/index.ts:5]:
```suggestion
const CLIENT_PREFIX = "NEXT_PUBLIC_" as const;
type ClientPrefix = typeof CLIENT_PREFIX;
```

File: packages/nextjs/index.ts [hunk 2]
```diff
@@ -1,67 +1,29 @@
...
+  TServer extends Record<string, ZodType>,
+  TClient extends Record<`${ClientPrefix}${string}`, ZodType>
+>({ runtimeEnv, ...opts }: Options<TServer, TClient>) {
+  return createEnvCore<ClientPrefix, TServer, TClient>({
     ...opts,
-    // @ts-expect-error TODO: Fix this
-    client: opts.client,
-    runtimeEnvStrict: opts.runtimeEnv,
-    // @ts-expect-error TODO: Fix this
     clientPrefix: "NEXT_PUBLIC_",
```
Comment (juliusmarminge) [inline packages/nextjs/index.ts:26]:
```suggestion
    clientPrefix: CLIENT_PREFIX,
```

**Review by juliusmarminge — APPROVED** [review]
Silly me - I think I used `Pick` now that I think about it - which often breaks some types..

Thanks for this! Works like a charm and much more maintainable!
