### PR TITLE
fix: handle empty env object type

### LINKED ISSUE #17: [Next.js] When not using client env variables, an `& { [x: string]: any }` union type appears
I don't use client variables very much in Next.js, but the empty configuration object is required in the `createEnv` function. Adding it adds an extra `& { [x: string]: any }` union type that breaks the env from telling you that a variable wasn't defined.

image
image

vs empty client config

image
image

### PR DESCRIPTION
**Pull request by chungweileong94**
fix #17
 
# Before:

image

# After:
image

### CODE REVIEW

File: packages/core/index.ts [hunk 1]
```diff
@@ -91,8 +91,8 @@ export interface StrictOptions<
 
 export function createEnv<
   TPrefix extends string,
-  TServer extends Record<string, ZodType>,
-  TClient extends Record<string, ZodType>
+  TServer extends Record<string, ZodType> = NonNullable<unknown>,
```
Comment (chungweileong94) [inline packages/core/index.ts:94]: This is my first time using `NonNullable<unknown>`, an alternative to `{}`, as the ESLint rule doesn't allow me to use it🤷

**Review by juliusmarminge — COMMENTED** [review]
can you add a regression test that validates this actually works?

File: packages/core/index.ts (hunk 1 above)
Comment (juliusmarminge) [reply packages/core/index.ts:94]: `Record<string, never>` is the type for `{}` that eslint allows fyi

File: packages/nextjs/index.ts [hunk 2]
```diff
@@ -6,8 +6,11 @@ const CLIENT_PREFIX = "NEXT_PUBLIC_" as const;
 type ClientPrefix = typeof CLIENT_PREFIX;
 
 interface Options<
-  TServer extends Record<string, ZodType>,
-  TClient extends Record<`${ClientPrefix}${string}`, ZodType>
+  TServer extends Record<string, ZodType> = NonNullable<unknown>,
+  TClient extends Record<
+    `${ClientPrefix}${string}`,
+    ZodType
+  > = NonNullable<unknown>
```
Comment (juliusmarminge) [inline packages/nextjs/index.ts:13]:
```suggestion
  TServer extends Record<string, ZodType>,
  TClient extends Record<`${ClientPrefix}${string}`, ZodType>
```

don't need defaults here

**Comment by juliusmarminge** [comment]
whopps - looks like i broke it and i can't seem to push to your branch to fix it back up :/

File: packages/core/index.ts (hunk 1 above)
Comment (chungweileong94) [reply packages/core/index.ts:94]: Yeah, I was using that originally, but unfortunately it didn't work in this case.

**Comment by chungweileong94** [comment]
> whopps - looks like i broke it and i can't seem to push to your branch to fix it back up :/

No worries, I will fix it once I'm available to do so.

**Comment by chungweileong94** [comment]
@juliusmarminge I'm a bit lost here, is it something wrong with the test on CI? It looks like it was trying to test against `/dist/**`, and I can't seem to reproduce the same error on my local.

**Comment by juliusmarminge** [comment]
Try pushing that to the tsconfig exclude maybe?

**Comment by chungweileong94** [comment]
> Try pushing that to the tsconfig exclude maybe?

Yeah, seems to work. Just weird that it didn't happen to my local environment. Thx for the help!

**Review by juliusmarminge — APPROVED** [review]

**Comment by juliusmarminge** [comment]
Oh we need a changeset too

**Comment by chungweileong94** [comment]
> Oh we need a changeset too

Done.

**Comment by chungweileong94** [comment]
Same type error happening again, probably something wrong with the CI.

File: .changeset/dirty-impalas-juggle.md [hunk 3]
```diff
@@ -0,0 +1,6 @@
+---
+"@t3-oss/env-core": minor
+"@t3-oss/env-nextjs": minor
```
Comment (juliusmarminge) [inline .changeset/dirty-impalas-juggle.md:3]:
```suggestion
"@t3-oss/env-core": patch
"@t3-oss/env-nextjs": patch
```

**Comment by juliusmarminge** [comment]
> Same type error happening again, probably something wrong with the CI.

Yea might be a bad turbo config so it's pulling a bad cache or something... i'll take a look! let's get this released :)
